### ISSUE TITLE
Allow to gather members from organization(s)

### ISSUE THREAD

**Issue by jwodder** [con/solidation#5]
(Taken from a comment in the code) Something like flattening of:

```python
members = list(set(sum(
    (   
        m.login for m in self.gh.get_organization(o).get_members()
        for o in set(r.split('/')[0] for r in repos)
    ),
    []
)))
```

**Comment by yarikoptic** [comment]
I think there might be no way to get private members, so we would be doomed to list explicitly. Asked on https://github.com/PyGithub/PyGithub/issues/2424

**Comment by jwodder** [comment]
@yarikoptic Do you still want this to fetch members for the organizations of individual repositories listed under `repositories`, or should it only fetch members of the organizations listed under `organizations`?  If we go with the former, and `repositories` contains a repo owner by a user rather than an organization, should that user be added to `members`?

**Comment by yarikoptic** [comment]
I am thinking to make it configurable as to make items for `organizations` to possibly become a structure (as you noted `OrgSpec` ) with a possible option to fetch its members, may be right away with regex (since why not)? e.g.

```yaml
organizations
  - name: dandi
    fetch_members: .*
```
and thus extend list of members possibly from some organizations but not the others. WDYT, or it would be overkill?

as for the latter question about user-vs-organization owner of the repo -- that is what I wonder if we ever want to automagically pick up all the individual users that way - I don't see a use case yet, do you?

**Comment by jwodder** [comment]
@yarikoptic

* Since `.*` would likely be the most common value for `fetch_members`, how about allowing the value to be either a boolean (to fetch all or no members) or a regex (to fetch only those members that match the regex)?
* You don't seem to have answered my question about whether listing `someorg/repo` under `repositories` but not listing `someorg` under `organizations` should cause `someorg`'s members to be included.
* This issue currently states that members for an organization should only be fetched if no members are specified.  Do you want to also add all organization members to `members` even if it's nonempty?  Should this be configurable, and, if so, how?

> as for the latter question about user-vs-organization owner of the repo -- that is what I wonder if we ever want to automagically pick up all the individual users that way - I don't see a use case yet, do you?

If we're tracking activity on some user's repo, it seems natural to include that user as a "member".

**Comment by yarikoptic** [comment]
> * Since `.*` would likely be the most common value for `fetch_members`, how about allowing the value to be either a boolean (to fetch all or no members) or a regex (to fetch only those members that match the regex)?

In general I don't see really a point in such sugaring which only makes it ambiguous on either `false` is a regex to match `false` or a `bool` value. Since here reliance on `yaml` syntax `false` vs `"false"` would make it programmatically unambiguous, I would be ok with it.

> * You don't seem to have answered my question about whether listing `someorg/repo` under `repositories` but not listing `someorg` under `organizations` should cause `someorg`'s members to be included.

No, we should not automagically include this way, since e.g. we would like to track `datalad/datalad-container` for `CON` but do not want to consider all `datalad` developers to be part of CON.

> * This issue currently states that members for an organization should only be fetched if no members are specified.  Do you want to also add all organization members to `members` even if it's nonempty?  Should this be configurable, and, if so, how?

The issue title stems from old(er) code/specification. With an explicit `organizations` section, I retitled the issue to correspond to a feature to *add* members from organizations. It should be independent on either members have explicit listing or not. Note: should deduplicate, i.e. if someone mentioned explicitly and also picked up from organization(s), shouldn't account somehow twice for that person.

> > as for the latter question about user-vs-organization owner of the repo -- that is what I wonder if we ever want to automagically pick up all the individual users that way - I don't see a use case yet, do you?
> 
> If we're tracking activity on some user's repo, it seems natural to include that user as a "member".

not really. Example: [Lykos153/AnnexRemote](https://github.com/Lykos153/AnnexRemote) where `Lykos153` is not a member of CON, and we just contribute to his personal repo.
